import { SamplerID } from '@lib/constants/SamplerData'

import { APIConfiguration } from './APIBuilder.types'

type OpenAICompatiblePreset = {
    // Template name, also stored as the connection's configName
    name: string
    // Shown in the template picker
    label: string
    description: string
    endpoint: string
    modelEndpoint: string
    priority: number
    link?: string
    icon?: string
    supportsImages?: boolean
}

// Most providers follow the OpenAI chat completions format, so one builder keeps
// every preset consistent and easy to fix when a provider changes something.
const openAICompatible = ({
    name,
    label,
    description,
    endpoint,
    modelEndpoint,
    priority,
    link,
    icon,
    supportsImages,
}: OpenAICompatiblePreset): APIConfiguration => ({
    version: 1,
    name,

    defaultValues: {
        endpoint,
        modelEndpoint,
        prefill: '',
        firstMessage: '',
        key: '',
        model: undefined,
    },

    features: {
        usePrefill: false,
        useFirstMessage: false,
        useKey: true,
        useModel: true,
        multipleModels: false,
    },

    request: {
        requestType: 'stream',
        samplerFields: [
            { externalName: 'max_context_length', samplerID: SamplerID.CONTEXT_LENGTH },
            { externalName: 'max_tokens', samplerID: SamplerID.GENERATED_LENGTH },
            { externalName: 'stream', samplerID: SamplerID.STREAMING },
            { externalName: 'temperature', samplerID: SamplerID.TEMPERATURE },
            { externalName: 'top_p', samplerID: SamplerID.TOP_P },
            { externalName: 'presence_penalty', samplerID: SamplerID.PRESENCE_PENALTY },
            { externalName: 'frequency_penalty', samplerID: SamplerID.FREQUENCY_PENALTY },
            { externalName: 'seed', samplerID: SamplerID.SEED },
        ],
        completionType: {
            type: 'chatCompletions',
            userRole: 'user',
            systemRole: 'system',
            assistantRole: 'assistant',
            contentName: 'content',
            supportsImages,
        },
        authHeader: 'Authorization',
        authPrefix: 'Bearer ',
        responseParsePattern: 'choices.0.delta.content',
        reasoningParsePattern: [
            'choices.0.delta.reasoning_content',
            'choices.0.delta.reasoning',
            'choices.0.delta.reasoning_details',
        ],
        useStop: true,
        stopKey: 'stop',
        promptKey: 'messages',
        removeLength: true,
    },

    payload: {
        type: 'openai',
    },

    model: {
        useModelContextLength: false,
        nameParser: 'id',
        contextSizeParser: '',
        modelListParser: 'data',
    },

    ui: {
        // keep the fields editable so a moved or regional host can be corrected
        editableCompletionPath: true,
        editableModelPath: true,
        selectableModel: true,
        display: {
            name: label,
            description,
            priority,
            icon: icon ?? 'openai',
            link,
        },
    },
})

export const providerPresets: APIConfiguration[] = [
    openAICompatible({
        name: 'DeepSeek',
        label: 'DeepSeek 深度求索',
        description: 'deepseek-chat / deepseek-reasoner，国内直连',
        endpoint: 'https://api.deepseek.com/v1/chat/completions',
        modelEndpoint: 'https://api.deepseek.com/v1/models',
        priority: 9900,
        link: 'https://platform.deepseek.com/api_keys',
    }),
    openAICompatible({
        name: 'Qwen (DashScope)',
        label: '阿里云百炼 · 通义千问',
        description: 'Qwen 全系，含 Qwen-VL 视觉模型',
        endpoint: 'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions',
        modelEndpoint: 'https://dashscope.aliyuncs.com/compatible-mode/v1/models',
        priority: 9800,
        supportsImages: true,
        link: 'https://bailian.console.aliyun.com/',
    }),
    openAICompatible({
        name: 'Zhipu GLM',
        label: '智谱 GLM',
        description: 'GLM-4 系列，含 GLM-4V',
        endpoint: 'https://open.bigmodel.cn/api/paas/v4/chat/completions',
        modelEndpoint: 'https://open.bigmodel.cn/api/paas/v4/models',
        priority: 9700,
        link: 'https://open.bigmodel.cn/usercenter/apikeys',
    }),
    openAICompatible({
        name: 'Moonshot Kimi',
        label: '月之暗面 Kimi',
        description: 'moonshot / kimi 模型',
        endpoint: 'https://api.moonshot.cn/v1/chat/completions',
        modelEndpoint: 'https://api.moonshot.cn/v1/models',
        priority: 9600,
        link: 'https://platform.moonshot.cn/console/api-keys',
    }),
    openAICompatible({
        name: 'SiliconFlow',
        label: '硅基流动 SiliconFlow',
        description: '一个 Key 用很多开源模型，国内直连',
        endpoint: 'https://api.siliconflow.cn/v1/chat/completions',
        modelEndpoint: 'https://api.siliconflow.cn/v1/models',
        priority: 9500,
        link: 'https://cloud.siliconflow.cn/account/ak',
    }),
    openAICompatible({
        name: 'Volcengine Ark (Doubao)',
        label: '火山方舟 · 豆包',
        description: '豆包大模型，模型名填接入点 ID',
        endpoint: 'https://ark.cn-beijing.volces.com/api/v3/chat/completions',
        modelEndpoint: 'https://ark.cn-beijing.volces.com/api/v3/models',
        priority: 9400,
        link: 'https://console.volcengine.com/ark',
    }),
    openAICompatible({
        name: 'Tencent Hunyuan',
        label: '腾讯混元',
        description: 'hunyuan 系列模型',
        endpoint: 'https://api.hunyuan.cloud.tencent.com/v1/chat/completions',
        modelEndpoint: 'https://api.hunyuan.cloud.tencent.com/v1/models',
        priority: 9300,
        link: 'https://console.cloud.tencent.com/hunyuan/api-key',
    }),
    openAICompatible({
        name: 'Baidu Qianfan',
        label: '百度千帆',
        description: '文心 / ERNIE 系列，需用新版 API Key',
        endpoint: 'https://qianfan.baidubce.com/v2/chat/completions',
        modelEndpoint: 'https://qianfan.baidubce.com/v2/models',
        priority: 9200,
        link: 'https://console.bce.baidu.com/iam/#/iam/apikey/list',
    }),
    openAICompatible({
        name: 'MiniMax',
        label: 'MiniMax 稀宇',
        description: 'MiniMax 文本模型',
        endpoint: 'https://api.minimax.chat/v1/chat/completions',
        modelEndpoint: 'https://api.minimax.chat/v1/models',
        priority: 9100,
        link: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
    }),
    openAICompatible({
        name: 'iFlytek Spark',
        label: '讯飞星火',
        description: 'spark 系列模型',
        endpoint: 'https://spark-api-open.xf-yun.com/v1/chat/completions',
        modelEndpoint: 'https://spark-api-open.xf-yun.com/v1/models',
        priority: 9000,
        link: 'https://console.xfyun.cn/services/bmx1',
    }),
    openAICompatible({
        name: 'StepFun',
        label: '阶跃星辰 StepFun',
        description: 'step 系列模型',
        endpoint: 'https://api.stepfun.com/v1/chat/completions',
        modelEndpoint: 'https://api.stepfun.com/v1/models',
        priority: 8900,
        link: 'https://platform.stepfun.com/interface-key',
    }),
    openAICompatible({
        name: '01.AI Yi',
        label: '零一万物 Yi',
        description: 'yi 系列模型',
        endpoint: 'https://api.lingyiwanwu.com/v1/chat/completions',
        modelEndpoint: 'https://api.lingyiwanwu.com/v1/models',
        priority: 8800,
        link: 'https://platform.lingyiwanwu.com/apikeys',
    }),
    openAICompatible({
        name: 'Gemini (OpenAI compatible)',
        label: 'Google Gemini',
        description: 'Gemini 官方 OpenAI 兼容接口，支持图片',
        endpoint: 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
        modelEndpoint: 'https://generativelanguage.googleapis.com/v1beta/openai/models',
        priority: 6000,
        supportsImages: true,
        icon: 'googleai',
        link: 'https://aistudio.google.com/app/apikey',
    }),
    openAICompatible({
        name: 'Groq',
        label: 'Groq',
        description: '推理速度很快，开源模型为主',
        endpoint: 'https://api.groq.com/openai/v1/chat/completions',
        modelEndpoint: 'https://api.groq.com/openai/v1/models',
        priority: 5900,
        icon: 'lightning',
        link: 'https://console.groq.com/keys',
    }),
    openAICompatible({
        name: 'xAI Grok',
        label: 'xAI Grok',
        description: 'grok 系列模型',
        endpoint: 'https://api.x.ai/v1/chat/completions',
        modelEndpoint: 'https://api.x.ai/v1/models',
        priority: 5800,
        link: 'https://console.x.ai',
    }),
    openAICompatible({
        name: 'Mistral',
        label: 'Mistral AI',
        description: 'mistral / magistral 系列',
        endpoint: 'https://api.mistral.ai/v1/chat/completions',
        modelEndpoint: 'https://api.mistral.ai/v1/models',
        priority: 5700,
        link: 'https://console.mistral.ai/api-keys',
    }),
    openAICompatible({
        name: 'Together AI',
        label: 'Together AI',
        description: '托管开源模型',
        endpoint: 'https://api.together.xyz/v1/chat/completions',
        modelEndpoint: 'https://api.together.xyz/v1/models',
        priority: 5600,
        link: 'https://api.together.ai/settings/api-keys',
    }),
    openAICompatible({
        name: 'Fireworks AI',
        label: 'Fireworks AI',
        description: '托管开源模型',
        endpoint: 'https://api.fireworks.ai/inference/v1/chat/completions',
        modelEndpoint: 'https://api.fireworks.ai/inference/v1/models',
        priority: 5500,
        link: 'https://fireworks.ai/account/api-keys',
    }),
    openAICompatible({
        name: 'DeepInfra',
        label: 'DeepInfra',
        description: '托管开源模型，按量计费',
        endpoint: 'https://api.deepinfra.com/v1/openai/chat/completions',
        modelEndpoint: 'https://api.deepinfra.com/v1/openai/models',
        priority: 5400,
        link: 'https://deepinfra.com/dash/api_keys',
    }),
    openAICompatible({
        name: 'Perplexity',
        label: 'Perplexity',
        description: '带联网搜索的模型',
        endpoint: 'https://api.perplexity.ai/chat/completions',
        modelEndpoint: 'https://api.perplexity.ai/models',
        priority: 5300,
        link: 'https://www.perplexity.ai/settings/api',
    }),
    openAICompatible({
        name: 'Cerebras',
        label: 'Cerebras',
        description: '极快推理，开源模型',
        endpoint: 'https://api.cerebras.ai/v1/chat/completions',
        modelEndpoint: 'https://api.cerebras.ai/v1/models',
        priority: 5200,
        icon: 'lightning',
        link: 'https://cloud.cerebras.ai',
    }),
    openAICompatible({
        name: 'SambaNova',
        label: 'SambaNova',
        description: '托管开源模型',
        endpoint: 'https://api.sambanova.ai/v1/chat/completions',
        modelEndpoint: 'https://api.sambanova.ai/v1/models',
        priority: 5100,
        link: 'https://cloud.sambanova.ai/apis',
    }),
    openAICompatible({
        name: 'Novita AI',
        label: 'Novita AI',
        description: '托管开源模型',
        endpoint: 'https://api.novita.ai/v3/openai/chat/completions',
        modelEndpoint: 'https://api.novita.ai/v3/openai/models',
        priority: 5000,
        link: 'https://novita.ai/settings/key-management',
    }),
    openAICompatible({
        name: 'LM Studio (local)',
        label: 'LM Studio（电脑本地）',
        description: '电脑上开 LM Studio 的本地服务，Key 随便填',
        endpoint: 'http://127.0.0.1:1234/v1/chat/completions',
        modelEndpoint: 'http://127.0.0.1:1234/v1/models',
        priority: 3000,
        icon: 'gear',
        link: 'https://lmstudio.ai/docs/app/api',
    }),
    openAICompatible({
        name: 'llama.cpp server (local)',
        label: 'llama.cpp 服务端',
        description: 'llama-server 的 /v1 接口',
        endpoint: 'http://127.0.0.1:8080/v1/chat/completions',
        modelEndpoint: 'http://127.0.0.1:8080/v1/models',
        priority: 2900,
        icon: 'gear',
        link: 'https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md',
    }),
    openAICompatible({
        name: 'vLLM (local)',
        label: 'vLLM 服务端',
        description: 'vLLM 的 OpenAI 兼容接口',
        endpoint: 'http://127.0.0.1:8000/v1/chat/completions',
        modelEndpoint: 'http://127.0.0.1:8000/v1/models',
        priority: 2800,
        icon: 'gear',
        link: 'https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html',
    }),
    openAICompatible({
        name: 'Jan (local)',
        label: 'Jan（电脑本地）',
        description: 'Jan 本地服务，Key 随便填',
        endpoint: 'http://127.0.0.1:1337/v1/chat/completions',
        modelEndpoint: 'http://127.0.0.1:1337/v1/models',
        priority: 2700,
        icon: 'gear',
        link: 'https://jan.ai/docs/local-api',
    }),
]
