export enum Storage {
    API = 'api-storage',
    EngineData = 'enginedata-storage',
    KV = 'kvdata-storage',
    TextFilter = 'textfilter-storage',
    AppMode = 'appmode-storage',
    BackgroundImage = 'background-image-storage',
    UserCard = 'usercard-storage',
    Instruct = 'instruct-storage',
    Logs = 'logstate-storage',
    Samplers = 'samplerstate-storage',
    TTS = 'tts-data-storage',
    ColorState = 'colorscheme-storage',
    TagHider = 'tag-hider-storage',
    CharacterSearch = 'storage-character-search',
    ChatStyle = 'storage-chat-text-styling',
    Language = 'storage-language',
    LorebookPreferences = 'storage-lorebook-preference',
    Wallet = 'wallet-storage',
    Social = 'social-life-storage',
    Relationships = 'relationship-storage',
    DeveloperContact = 'developer-contact-storage',
    ContentMode = 'content-mode-storage',
    DirectChat = 'direct-chat-storage',
    ModelScanDirectory = 'model-scan-directory',
}
